version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/cli"
    schedule:
      interval: "weekly"
    labels: ["dependencies", "go"]

  - package-ecosystem: "pip"
    directory: "/detection"
    schedule:
      interval: "weekly"
    labels: ["dependencies", "python"]

  - package-ecosystem: "npm"
    directory: "/vault"
    schedule:
      interval: "weekly"
    labels: ["dependencies", "node"]

  - package-ecosystem: "npm"
    directory: "/vault/sdk"
    schedule:
      interval: "weekly"
    labels: ["dependencies", "node"]

  - package-ecosystem: "npm"
    directory: "/api"
    schedule:
      interval: "weekly"
    labels: ["dependencies", "node"]

  - package-ecosystem: "npm"
    directory: "/rotation"
    schedule:
      interval: "weekly"
    labels: ["dependencies", "node"]

  - package-ecosystem: "npm"
    directory: "/dashboard"
    schedule:
      interval: "weekly"
    labels: ["dependencies", "node"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: ["dependencies", "github-actions"]
